# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adfb6ff6fe361dddf4e553cfbb59447bdc986145f92e6420edd511ae1aa92843a204acf277b74b0a7ab3185d9c6ebb332452f8a2228127b136e6855d9c33bd74

test:
  secret_key_base: 4517eacb80ba4a05a43d56b54ef0c4a15fe3ad9c99dbb8f7e038e93bda0d89fa521fe10787772fdb58c29ae4c1ccfff2c2bc65c50df60f67c895da690462b3f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
